(self.AMP=self.AMP||[]).push({n:"amp-analytics",f:(function(AMP){var k;function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};var ba=Object.prototype.toString;function ca(a){return"number"===typeof a&&isFinite(a)};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function p(){if(m.user)return m.user;throw Error("failed to call initLogConstructor");}function da(){if(m.dev)return m.dev;throw Error("failed to call initLogConstructor");};var ea=Object.prototype.hasOwnProperty;function fa(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function ga(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function ha(a,b){ga(a.documentElement,function(){return!!a.body},b)}function ia(a){return new Promise(function(b){ha(a,b)})}function ja(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}
function ka(a,b){if(a.closest)return a.closest(b);b=b.toUpperCase();return ja(a,function(a){return a.tagName==b})}function la(a){return a.closest?a.closest(".-amp-element,.i-amphtml-element"):ja(a,function(a){return na(a,".-amp-element,.i-amphtml-element")})}function na(a,b){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1}
function oa(a){var b=void 0,c=pa,d=b||function(a){return a},e=a.dataset;a=Object.create(null);var f=c?c:/^param(.+)/,g;for(g in e){var h=g.match(f);if(h){var l=h[1][0].toLowerCase()+h[1].substr(1);a[d(l)]=e[g]}}return a};function q(a,b){a=a.__AMP_TOP||a;var c=a.services&&a.services[b]&&a.services[b].obj;return c}function r(a,b){var c=qa(a);return c&&c.services&&c.services[b]&&c.services[b].obj}function ra(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&b.services&&b.services["url-replace"]&&b.services["url-replace"].obj?b.services["url-replace"].obj:null)return b}return r(a,"url-replace")}function t(a,b,c){a=a.__AMP_TOP||a;return sa(a,a,b,c)}
function qa(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=sa(b,b,"ampdoc").getAmpDoc(a)}return a.isSingleDoc()?a.win:a}function sa(a,b,c,d){var e=ta(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null});f.obj||(f.obj=d?new d(b):(void 0)(b),f.resolve&&f.resolve(f.obj));return f.obj}function ua(a,b){var c=va(a,b);if(c)return c;a=ta(a);var d,e=new Promise(function(a){d=a});a[b]={obj:null,promise:e,resolve:d};return e}
function va(a,b){if(a=ta(a)[b]){if(b=a.promise)return b;if(a.obj)return a.promise=Promise.resolve(a.obj)}return null}function ta(a){var b=a.services;b||(b=a.services={});return b};function wa(a,b,c){return xa(a,b,c).then(function(a){return p().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.",b,c,c,c)})}function xa(a,b,c){var d=va(a,b);return d?d:Promise.resolve().then(function(){return a.ampExtendedElements&&a.ampExtendedElements[c]?ua(a,b):ia(a.document).then(function(){return a.ampExtendedElements&&a.ampExtendedElements[c]?ua(a,b):null})})};function ya(a,b){for(var c=5,d=c||1,e={},f=0;f<d&&(e.matches=0,a=a.replace(/\${([^}]*)}/g,function(a){return function(c,d){a.matches++;return b(d)}}(e)),e.matches);e={matches:e.matches},f++);return a};var za=/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var x,Aa,Ba=/[?&]amp_js[^&]*/;
function y(a){var b;x||(x=self.document.createElement("a"),Aa=self.UrlCache||(self.UrlCache=Object.create(null)));var c=Aa[a];if(c)return c;x.href=a;x.protocol||(x.href=x.href);var d={href:x.href,protocol:x.protocol,host:x.host,hostname:x.hostname,port:"0"==x.port?"":x.port,pathname:x.pathname,search:x.search,hash:x.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=x.origin&&
"null"!=x.origin?x.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;var e=d;return b?e:Aa[a]=e}function Ca(a){"string"==typeof a&&(a=y(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function Da(a,b){var c;c=void 0===c?"source":c;p().assert(null!=a,"%s %s must be available",b,c);var d=a;p().assert(Ca(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function Ea(a){"string"==typeof a&&(a=y(a));return za.test(a.origin)};function z(a){return r(a,"viewer")};function Fa(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};function A(a){return wa(a,"crypto","amp-analytics")};function B(a,b){var c;a:{try{c=a.document.cookie;break a}catch(h){}c=void 0}var d=c;if(!d)return null;var e=d.split(";");for(a=0;a<e.length;a++){var f=e[a].trim(),g=f.indexOf("=");if(-1!=g&&decodeURIComponent(f.substring(0,g).trim())==b)return decodeURIComponent(f.substring(g+1).trim())}return null}
function Ga(a,b,c,d,e){"ampproject.org"==e&&(c="delete",d=0);b=encodeURIComponent(b)+"="+encodeURIComponent(c)+"; path=/"+(e?"; domain="+e:"")+"; expires="+(new Date(d)).toUTCString();try{a.document.cookie=b}catch(f){}};var C;
function Ha(a,b){if(!C){C=Object.create(null);if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(C[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var d=d.getAttribute("content").split(","),e=0;e<d.length;e++)-1!=c.indexOf(d[e])&&(C[d[e]]=!0);Object.assign(C,Ia(a))}a=
C;var f=a;return!!f[b]}function Ia(a){var b=B(a,"AMP_EXP"),c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function Ja(a,b,c){var d,e=a,f=c,g=d||!1;e.addEventListener(b,f,g);return function(){e&&e.removeEventListener(b,f,g);e=f=null}}function Ka(a,b,c){function d(a){f(a);g()}var e=a,f=c,g;g=function(){e&&e.removeEventListener(b,d,!1);f=d=e=null};e.addEventListener(b,d,!1);return g}
function La(a){var b,c;if(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)return Promise.resolve(a);var d=new Promise(function(d,f){var e=a.tagName;b="AUDIO"===e||"VIDEO"===e?Ka(a,"loadstart",d):Ka(a,"load",d);e&&(c=Ka(a,"error",f))}),d=d.then(function(){return a},Ma);return Na(d,b,c)}function Ma(a){(a=a.target)&&a.src&&(a=a.src);throw p().createError("Failed to load:",a);}
function Na(a,b,c){var d=void 0,e;e=void 0===d?a:q(self,"timer").timeoutPromise(d||0,a);b&&e.then(b,b);c&&e.then(c,c);return e};function D(){this.B=null}k=D.prototype;k.add=function(a){var b=this;this.B||(this.B=[]);this.B.push(a);return function(){b.remove(a)}};k.remove=function(a){this.B&&(a=this.B.indexOf(a),-1<a&&this.B.splice(a,1))};k.removeAll=function(){this.B&&(this.B.length=0)};k.fire=function(a){if(this.B)for(var b=this.B,c=0;c<b.length;c++)(0,b[c])(a)};k.getHandlerCount=function(){return this.B?this.B.length:0};var Oa,Pa="Webkit webkit Moz moz ms O o".split(" ");function Qa(a){var b=void 0;Oa||(Oa=Object.create(null));var c=Oa.display;if(!c||b){c="display";if(void 0===a.display){var d="D"+"display".slice(1);a:{for(var e=0;e<Pa.length;e++){var f=Pa[e]+d;if(void 0!==a[f]){d=f;break a}}d=""}var g=d;void 0!==a[g]&&(c=g)}b||(Oa.display=c)}return c}function Ra(a,b){var c,d=Qa(a.style);d&&(a.style[d]=c?b+c:b)}
function Sa(a){var b=!1;if(void 0===b){var c;c=(c=Qa(a.style))?a.style[c]:void 0;b="none"==c}Ra(a,b?"":"none")};function Ta(a){return r(a,"viewport")};function Ua(a,b){var c=0;"active"===a.type&&(c=5);return Math.min(b-a.time,c)}function Va(){this.ba=0;this.G=void 0}Va.prototype.push=function(a){this.G||(this.G=a);this.G.time<a.time&&(this.ba+=Ua(this.G,a.time),this.G=a)};Va.prototype.getTotalEngagedTime=function(a){var b=0;void 0!==this.G&&(b=this.ba+Ua(this.G,a));return b};var Wa=["mousedown","mouseup","mousemove","keydown","keyup"];
function Xa(a){this.ampdoc=a;this.ya=this.Ia.bind(this);this.fa=this.Y.bind(this);this.Ka=this.ma.bind(this);this.xa=this.Ba.bind(this);this.N=[];this.R=this.P=!1;this.ca=new Va;this.A=z(this.ampdoc);this.F=Ta(this.ampdoc);this.A.whenFirstVisible().then(this.Ha.bind(this))}k=Xa.prototype;k.Ha=function(){this.Ga=Date.now();this.Y();for(var a=0;a<Wa.length;a++)this.N.push(Ja(this.ampdoc.getRootNode(),Wa[a],this.fa));this.N.push(this.A.onVisibilityChanged(this.xa));this.F.onScroll(this.fa)};
function Ya(a){var b=Date.now()-a.Ga;return 0<b?b:0}k.Ia=function(){this.R=this.P=!1};k.Y=function(){this.P||(this.P=!0,this.R=!1,Za(this,"active"))};k.ma=function(){this.R||(this.R=!0,this.P=!1,Za(this,"inactive"))};function Za(a,b){var c=Ya(a),d=Math.floor(c/1E3),e=1E3-c%1E3;setTimeout(a.ya,e);a.ca.push({type:b,time:d})}k.Ba=function(){this.A.isVisible()?this.Y():this.ma()};k.La=function(){for(var a=0;a<this.N.length;a++){var b=this.N[a];"function"===typeof b&&b()}this.N=[]};
k.getTotalEngagedTime=function(){var a=Math.floor(Ya(this)/1E3);return this.ca.getTotalEngagedTime(a)};function $a(a){var b=new Image;b.src=a;b.width=1;b.height=1;La(b).then(function(){}).catch(function(){p().warn("amp-analytics.Transport","Response unparseable or failed to send image request",a)})}function ab(a,b){if(!a.XMLHttpRequest)return!1;var c=new a.XMLHttpRequest;if(!("withCredentials"in c))return!1;c.open("POST",b,!0);c.withCredentials=!0;c.setRequestHeader("Content-Type","text/plain");c.onreadystatechange=function(){};c.send("");return!0}
function bb(a,b){Da(b,"amp-analytics request");var c=a.document.createElement("iframe");Ra(c,"none");c.onload=c.onerror=function(){q(a,"timer").delay(function(){c.parentElement&&c.parentElement.removeChild(c)},5E3)};p().assert(y(b).origin!=y(a.location.href).origin,"Origin of iframe request must not be equal to the document origin. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.");c.setAttribute("amp-analytics","");c.setAttribute("sandbox","allow-scripts allow-same-origin");
c.src=b;a.document.body.appendChild(c)};function cb(a){this.win=a;this.U=null;this.X=Object.create(null)}cb.prototype.get=function(a,b,c){var d=this,e;e="string"==typeof a?{scope:a}:a;p().assert(/^[a-zA-Z0-9-_.]+$/.test(e.scope),"The client id name must only use the characters [a-zA-Z0-9-_.]+\nInstead found: %s",e.scope);return b.then(function(){return z(d.win.document).whenFirstVisible()}).then(function(){return db(d,e,c||b)})};
function db(a,b,c){var d=y(a.win.location.href);return Ea(d)?Promise.all([eb(a,c),A(a.win)]).then(function(a){var c=a[0],e=a[1];return e.sha384Base64(c+fb(d)+b.scope)}):gb(a,b,c)}function hb(a,b,c){var d=Date.now()+31536E6;a:{var e=b,f=d,g={highestAvailableDomain:!0};if(g&&g.highestAvailableDomain)for(var g=a.location.hostname.split("."),h=g[g.length-1],l=g.length-2;0<=l;l--)if(h=g[l]+"."+h,Ga(a,e,c,f,h),B(a,e)==c)break a;Ga(a,e,c,f,void 0)}}
function gb(a,b,c){var d=a.win,e=b.scope,f=B(d,e);if(!f&&!b.createCookieIfNotPresent)return Promise.resolve(null);if(a.X[e])return a.X[e];if(f)return/^amp-/.test(f)&&hb(d,e,f),Promise.resolve(f);var g=A(d).then(function(a){return a.sha384Base64(ib(d))}).then(function(a){return"amp-"+a});Promise.all([g,c]).then(function(a){var b=a[0],c=B(d,e);c||hb(d,e,b)});return a.X[e]=g}
function fb(a){p().assert(Ea(a),"Expected proxy origin %s",a.origin);"string"==typeof a&&(a=y(a));if(Ea(a)){var b=a.pathname.split("/"),c=b[1];p().assert("c"==c||"v"==c,"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);p().assert(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(Ba,"").replace(/^[?&]/,""))?"?"+c:"":"";a=b+c+(a.hash||"")}else a=a.href;
return y(a).origin}function eb(a,b){if(a.U)return a.U;var c=a.win;return a.U=jb(c).then(function(a){var d=!1,f;a&&!mb(a)?(f=Promise.resolve(a.cid),nb(a)&&(d=!0)):(f=A(c).then(function(a){return a.sha384Base64(ib(c))}),d=!0);d&&f.then(function(a){ob(c,b,a)});return f})}function ob(a,b,c){var d=z(a.document);a.parent&&a.parent!=a?d.baseCid(pb(c)):b.then(function(){try{a.localStorage.setItem("amp-cid",pb(c))}catch(e){}})}function pb(a){return JSON.stringify({time:Date.now(),cid:a})}
function jb(a){var b;try{b=a.localStorage.getItem("amp-cid")}catch(e){}var c=z(a.document),d=Promise.resolve(b);!b&&a.parent&&a.parent!=a&&(d=c.baseCid());return d.then(function(a){if(!a)return null;a=JSON.parse(a);return{time:a.time,cid:a.cid}})}function mb(a){var b=a.time,c=Date.now();return b+31536E6<c}function nb(a){a=a.time;var b=Date.now();return a+864E5<b}
function ib(a){var b;a.crypto&&a.crypto.getRandomValues?(b=new Uint8Array(16),a.crypto.getRandomValues(b)):b=null;return b?b:String(a.location.href+Date.now()+a.Math.random()+a.screen.width+a.screen.height)};var qb=this;function rb(a,b){a=a.split(".");var c=window||qb;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b}
function sb(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function tb(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.u=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}}function E(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)}function F(a,b){this.b=a|0;this.a=b|0}var ub={},G={};
function vb(a){return-128<=a&&128>a?E(ub,a,function(a){return new F(a|0,0>a?-1:0)}):new F(a|0,0>a?-1:0)}function H(a){return isNaN(a)?I():a<=-wb?J():a+1>=wb?xb():0>a?K(H(-a)):new F(a%L|0,a/L|0)}var L=4294967296,wb=L*L/2;function I(){return E(G,yb,function(){return vb(0)})}function M(){return E(G,zb,function(){return vb(1)})}function Ab(){return E(G,Bb,function(){return vb(-1)})}function xb(){return E(G,Cb,function(){return new F(-1,2147483647)})}
function J(){return E(G,Db,function(){return new F(0,-2147483648)})}function Eb(){return E(G,Fb,function(){return vb(16777216)})}
F.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(N(this))return"0";if(0>this.a){if(O(this,J())){var b=H(a),c=Q(this,b),b=R(S(c,b),K(this));return c.toString(a)+b.b.toString(a)}return"-"+K(this).toString(a)}for(var c=H(Math.pow(a,6)),b=this,d="";;){var e=Q(b,c),f=(R(b,K(S(e,c))).b>>>0).toString(a),b=e;if(N(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function Gb(a){return 0<=a.b?a.b:L+a.b}function N(a){return 0==a.a&&0==a.b}
function O(a,b){return a.a==b.a&&a.b==b.b}function Hb(a,b){if(O(a,b))return 0;var c=0>a.a,d=0>b.a;return c&&!d?-1:!c&&d?1:0>R(a,K(b)).a?-1:1}function K(a){return O(a,J())?J():R(new F(~a.b,~a.a),M())}function R(a,b){var c=a.a>>>16,d=a.a&65535,e=a.b>>>16,f=b.a>>>16,g=b.a&65535,h=b.b>>>16;a=0+((a.b&65535)+(b.b&65535));h=0+(a>>>16)+(e+h);e=0+(h>>>16)+(d+g);return new F((h&65535)<<16|a&65535,(0+(e>>>16)+(c+f)&65535)<<16|e&65535)}
function S(a,b){if(N(a)||N(b))return I();if(O(a,J()))return 1==(b.b&1)?J():I();if(O(b,J()))return 1==(a.b&1)?J():I();if(0>a.a)return 0>b.a?S(K(a),K(b)):K(S(K(a),b));if(0>b.a)return K(S(a,K(b)));if(0>Hb(a,Eb())&&0>Hb(b,Eb()))return H((a.a*L+Gb(a))*(b.a*L+Gb(b)));var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,h=b.b>>>16;b=b.b&65535;var l,n,w,u;u=0+a*b;w=0+(u>>>16)+e*b;n=0+(w>>>16);w=(w&65535)+a*h;n=n+(w>>>16)+d*b;l=0+(n>>>16);n=(n&65535)+e*h;l+=n>>>16;n=(n&65535)+a*g;return new F((w&
65535)<<16|u&65535,(l+(n>>>16)+(c*b+d*h+e*g+a*f)&65535)<<16|n&65535)}
function Q(a,b){if(N(b))throw Error("division by zero");if(N(a))return I();if(O(a,J())){if(O(b,M())||O(b,Ab()))return J();if(O(b,J()))return M();var c;c=1;if(0==c)c=a;else{var d=a.a;c=32>c?new F(a.b>>>c|d<<32-c,d>>c):new F(d>>c-32,0<=d?0:-1)}c=Q(c,b);d=1;if(0!=d){var e=c.b;c=32>d?new F(e<<d,c.a<<d|e>>>32-d):new F(0,e<<d-32)}if(O(c,I()))return 0>b.a?M():Ab();a=R(a,K(S(b,c)));return R(c,Q(a,b))}if(O(b,J()))return I();if(0>a.a)return 0>b.a?Q(K(a),K(b)):K(Q(K(a),b));if(0>b.a)return K(Q(a,K(b)));for(d=
I();0<=Hb(a,b);){c=Math.max(1,Math.floor((a.a*L+Gb(a))/(b.a*L+Gb(b))));for(var e=Math.ceil(Math.log(c)/Math.LN2),e=48>=e?1:Math.pow(2,e-48),f=H(c),g=S(f,b);0>g.a||0<Hb(g,a);)c-=e,f=H(c),g=S(f,b);N(f)&&(f=M());d=R(d,f);a=R(a,K(g))}return d}var Cb=1,Db=2,yb=3,zb=4,Bb=5,Fb=6;
function Ib(a,b){this.g=128;this.h=void 0!==qb.Uint8Array?new Uint8Array(128):Array(128);this.j=this.f=0;this.c=[];this.l=a;this.s=[];this.o=Jb(b);this.i=!1;this.j=this.f=0;a=this.o;b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];a=c}else a=[];this.c=a;this.i=!1}tb(Ib,function(){this.g=-1});for(var Kb=[],Lb=0;127>Lb;Lb++)Kb[Lb]=0;var Mb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)}([128],Kb);
function Nb(a,b,c){c=void 0!==c?c:b.length;if(a.i)throw Error("this hasher needs to be reset");var d=a.f;if("string"==typeof b)for(var e=0;e<c;e++){var f=b.charCodeAt(e);if(255<f)throw Error("Characters must be in range [0,255]");a.h[d++]=f;d==a.g&&(Ob(a),d=0)}else if(e=sb(b),"array"==e||"object"==e&&"number"==typeof b.length)for(e=0;e<c;e++){f=b[e];if("number"!=typeof f||0>f||255<f||f!=(f|0))throw Error("message must be a byte array");a.h[d++]=f;d==a.g&&(Ob(a),d=0)}else throw Error("message must be string or array");
a.f=d;a.j+=c}
function Ob(a){for(var b=a.h,c=a.s,d=0;16>d;d++){var e=8*d;c[d]=new F(b[e+4]<<24|b[e+5]<<16|b[e+6]<<8|b[e+7],b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3])}for(d=16;80>d;d++){var e=c[d-15],b=e.b,e=e.a,f=c[d-2],g=f.b,f=f.a;c[d]=a.m(c[d-16],c[d-7],new F(b>>>1^e<<31^b>>>8^e<<24^b>>>7^e<<25,e>>>1^b<<31^e>>>8^b<<24^e>>>7),new F(g>>>19^f<<13^f>>>29^g<<3^g>>>6^f<<26,f>>>19^g<<13^g>>>29^f<<3^f>>>6))}for(var b=a.c[0],e=a.c[1],g=a.c[2],f=a.c[3],h=a.c[4],l=a.c[5],n=a.c[6],w=a.c[7],d=0;80>d;d++)var u=b.b,v=b.a,u=R(new F(u>>>
28^v<<4^v>>>2^u<<30^v>>>7^u<<25,v>>>28^u<<4^u>>>2^v<<30^u>>>7^v<<25),new F(b.b&e.b|e.b&g.b|b.b&g.b,b.a&e.a|e.a&g.a|b.a&g.a)),v=h.b,P=h.a,kb=h.b,lb=h.a,v=a.m(w,new F(v>>>14^P<<18^v>>>18^P<<14^P>>>9^v<<23,P>>>14^v<<18^P>>>18^v<<14^v>>>9^P<<23),new F(kb&l.b|~kb&n.b,lb&l.a|~lb&n.a),Pb[d],c[d]),w=n,n=l,l=h,h=R(f,v),f=g,g=e,e=b,b=R(v,u);a.c[0]=R(a.c[0],b);a.c[1]=R(a.c[1],e);a.c[2]=R(a.c[2],g);a.c[3]=R(a.c[3],f);a.c[4]=R(a.c[4],h);a.c[5]=R(a.c[5],l);a.c[6]=R(a.c[6],n);a.c[7]=R(a.c[7],w)}
Ib.prototype.m=function(a,b,c){for(var d=(a.b^2147483648)+(b.b^2147483648),e=a.a+b.a,f=arguments.length-1;2<=f;--f)d+=arguments[f].b^2147483648,e+=arguments[f].a;arguments.length&1&&(d+=2147483648);e+=arguments.length>>1;e+=Math.floor(d/4294967296);return new F(d,e)};function Jb(a){for(var b=[],c=0;c<a.length;c+=2)b.push(new F(a[c+1],a[c]));return b}
var Pb=Jb([1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591]);function Qb(){Ib.call(this,6,Rb)}tb(Qb,Ib);var Rb=[3418070365,3238371032,1654270250,914150663,2438529370,812702999,355462360,4144912697,1731405415,4290775857,2394180231,1750603025,3675008525,1694076839,1203062813,3204075428],Sb=null,Tb=null;
rb("ampBase64",function(a){if(!Sb){Sb={};Tb={};for(var b=0;65>b;b++)Sb[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b),Tb[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(b)}for(var b=Tb,c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,h=d+2<a.length,l=h?a[d+2]:0,n=e>>2,e=(e&3)<<4|g>>4,g=(g&15)<<2|l>>6,l=l&63;h||(l=64,f||(g=64));c.push(b[n],b[e],b[g],b[l])}return c.join("")});
rb("ampSha384Digest",function(a){var b=new Qb;Nb(b,a);if(b.i)throw Error("this hasher needs to be reset");var c=8*b.j;112>b.f?Nb(b,Mb,112-b.f):Nb(b,Mb,b.g-b.f+112);for(a=127;112<=a;a--)b.h[a]=c&255,c/=256;Ob(b);var c=0,d=Array(8*b.l);for(a=0;a<b.l;a++){for(var e=b.c[a],f=e.a,e=e.b,g=24;0<=g;g-=8)d[c++]=f>>g&255;for(g=24;0<=g;g-=8)d[c++]=e>>g&255}b.i=!0;return d});function Ub(a){this.ua=a.crypto?a.crypto.subtle||a.crypto.webkitSubtle||null:null}Ub.prototype.sha384=function(a){if(this.ua)try{return this.ua.digest({name:"SHA-384"},a instanceof Uint8Array?a:Fa(a)).then(function(a){return[].slice.call(new Uint8Array(a))},function(b){b.message&&0>b.message.indexOf("secure origin")&&da().error("Crypto","SubtleCrypto failed, fallback to closure lib.",b);return ampSha384Digest(a)})}catch(b){da().error("Crypto","SubtleCrypto failed, fallback to closure lib.",b)}return Promise.resolve(ampSha384Digest(a))};
Ub.prototype.sha384Base64=function(a){return this.sha384(a).then(function(a){return ampBase64(a)})};Ub.prototype.uniform=function(a){return this.sha384(a).then(function(a){for(var b=0,d=2;0<=d;d--)b=(b+a[d])/256;return b})};var Vb=/^(?:([^\s]*)(\([^)]*\))|[^]+)$/;function T(a,b){this.filter=a;this.allowNull=!!b}function Wb(a,b,c){this.vars=a;this.iterations=void 0===b?2:b;this.noEncode=!!c}function Xb(a,b,c){b=Number(b);var d=a.length;p().assert(ca(b),"Start index "+b+"in substr filter should be a number");c&&(d=Number(c),p().assert(ca(d),"Length "+d+" in substr filter should be a number"));return a.substr(b,d)}function Yb(a,b){return a||p().assertString(b)}
function U(a){this.wa=a;this.ka=fa();V(this,"default",new T(Yb,!0));V(this,"substr",new T(Xb));V(this,"trim",new T(function(a){return a.trim()}));V(this,"json",new T(function(a){return JSON.stringify(a)}));V(this,"toLowerCase",new T(function(a){return a.toLowerCase()}));V(this,"toUpperCase",new T(function(a){return a.toUpperCase()}));V(this,"not",new T(function(a){return String(!a)}));V(this,"base64",new T(function(a){return btoa(a)}));V(this,"hash",new T(this.Ca.bind(this)));V(this,"if",new T(function(a,
c,d){return a?c:d},!0))}function V(a,b,c){a.ka[b]=c}function Zb(a,b){if(!b)return null;var c=b.split(":"),d=c.shift();p().assert(d,"Filter "+name+" is invalid.");return{filter:p().assert(a.ka[d],"Unknown filter: "+d),args:c}}
function $b(a,b,c){if(!Ha(a.wa,"variable-filters"))return Promise.resolve(b);b=Promise.resolve(b);for(var d={},e=0;e<c.length;d={filter:d.filter,args:d.args},e++){var f=Zb(a,c[e].trim());d.filter=f.filter;d.args=f.args;d.filter&&(b=b.then(function(a){return function(b){return null!=b||a.filter.allowNull?(a.args.unshift(b),a.filter.filter.apply(null,a.args)):null}}(d)))}return b}
U.prototype.expandTemplate=function(a,b){var c=this;if(0>b.iterations)return p().error("Analytics.Variables","Maximum depth reached while expanding variables. Please ensure that the variables are not recursive."),Promise.resolve(a);var d=[],e=a.replace(/\${([^}]*)}/g,function(a,g){var f=g.split("|"),l=f.shift().trim();if(!l)return Promise.resolve("");g=ac(l);var n=g.name,w=g.argList,u=b.vars[n]||"";g="string"==typeof u?c.expandTemplate(u,new Wb(b.vars,b.iterations-1,b.noEncode)):Promise.resolve(u);
g=g.then(function(a){return $b(c,a,f)}).then(function(a){var d=b.noEncode?a:c.encodeVars(a,n);return d?d+w:d}).then(function(b){e=e.replace(a,b)});d.push(g);return a});return Promise.all(d).then(function(){return e})};function ac(a){if(!a)return{name:"",argList:""};var b=a.match(Vb);p().assert(b,"Variable with invalid format found: "+a);return{name:b[1]||b[0],argList:b[2]||""}}
U.prototype.encodeVars=function(a){if(!a)return"";if(Array.isArray(a))return a.map(encodeURIComponent).join(",");a=ac(String(a));var b=a.argList;return encodeURIComponent(a.name)+b};U.prototype.Ca=function(a){return A(this.wa).then(function(b){return b.sha384Base64(a)})};var bc={"default":{transport:{beacon:!0,xhrpost:!0,image:!0},vars:{accessReaderId:"ACCESS_READER_ID",adNavTiming:"AD_NAV_TIMING",adNavType:"AD_NAV_TYPE",adRedirectCount:"AD_NAV_REDIRECT_COUNT",ampdocHost:"AMPDOC_HOST",ampdocHostname:"AMPDOC_HOSTNAME",ampdocUrl:"AMPDOC_URL",ampVersion:"AMP_VERSION",authdata:"AUTHDATA",availableScreenHeight:"AVAILABLE_SCREEN_HEIGHT",availableScreenWidth:"AVAILABLE_SCREEN_WIDTH",backgroundState:"BACKGROUND_STATE",browserLanguage:"BROWSER_LANGUAGE",canonicalHost:"CANONICAL_HOST",
canonicalHostname:"CANONICAL_HOSTNAME",canonicalPath:"CANONICAL_PATH",canonicalUrl:"CANONICAL_URL",clientId:"CLIENT_ID",contentLoadTime:"CONTENT_LOAD_TIME",counter:"COUNTER",documentCharset:"DOCUMENT_CHARSET",documentReferrer:"DOCUMENT_REFERRER",domainLookupTime:"DOMAIN_LOOKUP_TIME",domInteractiveTime:"DOM_INTERACTIVE_TIME",navRedirectCount:"NAV_REDIRECT_COUNT",navTiming:"NAV_TIMING",navType:"NAV_TYPE",pageDownloadTime:"PAGE_DOWNLOAD_TIME",pageLoadTime:"PAGE_LOAD_TIME",pageViewId:"PAGE_VIEW_ID",queryParam:"QUERY_PARAM",
random:"RANDOM",redirectTime:"REDIRECT_TIME",screenColorDepth:"SCREEN_COLOR_DEPTH",screenHeight:"SCREEN_HEIGHT",screenWidth:"SCREEN_WIDTH",scrollHeight:"SCROLL_HEIGHT",scrollLeft:"SCROLL_LEFT",scrollTop:"SCROLL_TOP",scrollWidth:"SCROLL_WIDTH",serverResponseTime:"SERVER_RESPONSE_TIME",sourceUrl:"SOURCE_URL",sourceHost:"SOURCE_HOST",sourceHostname:"SOURCE_HOSTNAME",sourcePath:"SOURCE_PATH",tcpConnectTime:"TCP_CONNECT_TIME",timestamp:"TIMESTAMP",timezone:"TIMEZONE",title:"TITLE",totalEngagedTime:"TOTAL_ENGAGED_TIME",
viewer:"VIEWER",viewportHeight:"VIEWPORT_HEIGHT",viewportWidth:"VIEWPORT_WIDTH"}},afsanalytics:{vars:{server:"www",websiteid:"xxxxxxxx",event:"click",clicklabel:"clicked from AMP page"},transport:{beacon:!1,xhrpost:!1,image:!0},requests:{host:"//${server}.afsanalytics.com",base:"${host}/cgi_bin/",pageview:"${base}connect.cgi?usr=${websiteid}Pauto&js=1&amp=1&title=${title}&url=${canonicalUrl}&refer=${documentReferrer}&resolution=${screenWidth}x${screenHeight}&color=${screenColorDepth}&Tips=${random}",
click:"${base}click.cgi?usr=${websiteid}&event=${event}&exit=${clicklabel}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}}},atinternet:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{base:"https://${log}${domain}/hit.xiti?s=${site}&ts=${timestamp}&r=${screenWidth}x${screenHeight}x${screenColorDepth}&re=${availableScreenWidth}x${availableScreenHeight}",suffix:"&medium=amp&${extraUrlParams}&ref=${documentReferrer}",pageview:"${base}&p=${title}&s2=${level2}${suffix}",click:"${base}&pclick=${title}&s2click=${level2}&p=${label}&s2=${level2Click}&type=click&click=${type}${suffix}"}},
burt:{vars:{trackingKey:"ignore",category:"",subCategory:""},requests:{host:"//${trackingKey}.c.richmetrics.com/",base:"${host}imglog?e=${trackingKey}&pi=${trackingKey}|${pageViewId}|${canonicalPath}|${clientId(burt-amp-user-id)}&ui=${clientId(burt-amp-user-id)}&v=amp&ts=${timestamp}&sn=${requestCount}&",pageview:"${base}type=page&ca=${category}&sc=${subCategory}&ln=${browserLanguage}&lr=${documentReferrer}&eu=${sourceUrl}&tz=${timezone}&pd=${scrollWidth}x${scrollHeight}&sd=${screenWidth}x${screenHeight}&wd=${availableScreenWidth}x${availableScreenHeight}&ws=${scrollLeft}x${scrollTop}",
pageping:"${base}type=pageping"},triggers:{pageview:{on:"visible",request:"pageview"},pageping:{on:"timer",timerSpec:{interval:15,maxTimerLength:1200},request:"pageping"}},transport:{beacon:!1,xhrpost:!1,image:!0}},chartbeat:{requests:{host:"https://ping.chartbeat.net",basePrefix:"/ping?h=${domain}&p=${canonicalPath}&u=${clientId(_cb)}&d=${canonicalHost}&g=${uid}&g0=${sections}&g1=${authors}&g2=${zone}&g3=${sponsorName}&g4=${contentType}&c=120&x=${scrollTop}&y=${scrollHeight}&j=${decayTime}&R=1&W=0&I=0&E=${totalEngagedTime}&r=${documentReferrer}&t=${pageViewId}${clientId(_cb)}&b=${pageLoadTime}&i=${title}&T=${timestamp}&tz=${timezone}&C=2",
baseSuffix:"&_",interval:"${host}${basePrefix}${baseSuffix}",anchorClick:"${host}${basePrefix}${baseSuffix}"},triggers:{trackInterval:{on:"timer",timerSpec:{interval:15,maxTimerLength:7200},request:"interval",vars:{decayTime:30}},trackAnchorClick:{on:"click",selector:"a",request:"anchorClick",vars:{decayTime:30}}},transport:{beacon:!1,xhrpost:!1,image:!0}},clicky:{vars:{site_id:""},requests:{base:"https://in.getclicky.com/in.php?site_id=${site_id}",baseSuffix:"&mime=${contentType}&x=${random}",pageview:"${base}&res=${screenWidth}x${screenHeight}&lang=${browserLanguage}&secure=1&type=pageview&href=${canonicalPath}&title=${title}${baseSuffix}",
interval:"${base}&type=ping${baseSuffix}"},triggers:{defaultPageview:{on:"visible",request:"pageview"},interval:{on:"timer",timerSpec:{interval:60,maxTimerLength:600},request:"interval"}},transport:{beacon:!1,xhrpost:!1,image:!0}},colanalytics:{requests:{host:"https://ase.clmbtech.com",base:"${host}/message",pageview:"${base}?cid=${id}&val_101=${id}&val_101=${canonicalPath}&ch=${canonicalHost}&uuid=${uid}&au=${authors}&zo=${zone}&sn=${sponsorName}&ct=${contentType}&st=${scrollTop}&sh=${scrollHeight}&dct=${decayTime}&tet=${totalEngagedTime}&dr=${documentReferrer}&plt=${pageLoadTime}&val_108=${title}&val_120=3"},
triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},comscore:{vars:{c2:"1000001"},requests:{host:"https://sb.scorecardresearch.com",base:"${host}/b?",pageview:"${base}c1=2&c2=${c2}&rn=${random}&c8=${title}&c7=${canonicalUrl}&c9=${documentReferrer}&cs_c7amp=${ampdocUrl}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},cxense:{requests:{host:"https://scomcluster.cxense.com",base:"${host}/Repo/rep.gif",
pageview:"${base}?ver=1&typ=pgv&sid=${siteId}&ckp=${clientId(cX_P)}&loc=${sourceUrl}&rnd=${random}&ref=${documentReferrer}&ltm=${timestamp}&wsz=${screenWidth}x${screenHeight}&bln=${browserLanguage}&chs=${documentCharset}&col=${screenColorDepth}&tzo=${timezone}&cp_cx_channel=amp"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},googleanalytics:{vars:{eventValue:"0",documentLocation:"SOURCE_URL",clientId:"CLIENT_ID(AMP_ECID_GOOGLE)",dataSource:"AMP"},
requests:{host:"https://www.google-analytics.com",basePrefix:"v=1&_v=a1&ds=${dataSource}&aip=true&_s=${requestCount}&dt=${title}&sr=${screenWidth}x${screenHeight}&_utmht=${timestamp}&cid=${clientId}&tid=${account}&dl=${documentLocation}&dr=${documentReferrer}&sd=${screenColorDepth}&ul=${browserLanguage}&de=${documentCharset}",baseSuffix:"&a=${pageViewId}&z=${random}",pageview:"${host}/r/collect?${basePrefix}&t=pageview&jid=${random}&_r=1${baseSuffix}",event:"${host}/collect?${basePrefix}&t=event&jid=&ec=${eventCategory}&ea=${eventAction}&el=${eventLabel}&ev=${eventValue}${baseSuffix}",
social:"${host}/collect?${basePrefix}&t=social&jid=&sa=${socialAction}&sn=${socialNetwork}&st=${socialTarget}${baseSuffix}",timing:"${host}/collect?${basePrefix}&t=timing&jid=&plt=${pageLoadTime}&dns=${domainLookupTime}&tcp=${tcpConnectTime}&rrt=${redirectTime}&srt=${serverResponseTime}&pdt=${pageDownloadTime}&clt=${contentLoadTime}&dit=${domInteractiveTime}${baseSuffix}"},triggers:{performanceTiming:{on:"visible",request:"timing",sampleSpec:{sampleOn:"${clientId}",threshold:1}}},extraUrlParamsReplaceMap:{dimension:"cd",
metric:"cm"},optout:"_gaUserPrefs.ioo"},googleconversion:{requests:{conversion:"https://www.googleadservices.com/pagead/conversion/${google_conversion_id}/?cv=amp1&value=${google_conversion_value}&currency_code=${google_conversion_currency}&label=${google_conversion_label}&random=${random}&url=${sourceUrl}&fst=${pageViewId}&num=${counter(googleconversion)}&fmt=3&async=3&bg=${google_conversion_color}&u_h=${screenHeight}&u_w=${screenWidth}&u_ah=${viewportHeight}&u_aw=${viewportWidth}&u_cd=${screenColorDepth}&u_tz=${timezone}&tiba=${title}&guid=ON&script=0"},
transport:{beacon:!1,xhrpost:!1,image:!0}},krux:{requests:{beaconHost:"https://beacon.krxd.net",timing:"t_navigation_type=0&t_dns=${domainLookupTime}&t_tcp=${tcpConnectTime}&t_http_request=${serverResponseTime}&t_http_response=${pageDownloadTime}&t_content_ready=${contentLoadTime}&t_window_load=${pageLoadTime}&t_redirect=${redirectTime}",common:"source=amp&confid=${confid}&_kpid=${pubid}&_kcp_s=${site}&_kcp_sc=${section}&_kcp_ssc=${subsection}&_kcp_d=${canonicalHost}&_kpref_=${documentReferrer}&_kua_kx_amp_client_id=${clientId(_kuid_)}&_kua_kx_lang=${browserLanguage}&_kua_kx_tech_browser_language=${browserLanguage}&_kua_kx_tz=${timezone}",
pageview:"${beaconHost}/pixel.gif?${common}&${timing}",event:"${beaconHost}/event.gif?${common}&${timing}&pageview=false"},transport:{beacon:!1,xhrpost:!1,image:!0},extraUrlParamsReplaceMap:{"user.":"_kua_","page.":"_kpa_"}},lotame:{requests:{pageview:"https://bcp.crwdcntrl.net/amp?c=${account}&pv=y"},triggers:{"track pageview":{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},mediametrie:{requests:{host:"https://prof.estat.com/m/web",pageview:"${host}/${serial}?c=${level1}&dom=${ampdocUrl}&enc=${documentCharset}&l3=${level3}&l4=${level4}&n=${random}&p=${level2}&r=${documentReferrer}&sch=${screenHeight}&scw=${screenWidth}&tn=amp&v=1&vh=${availableScreenHeight}&vw=${availableScreenWidth}"},
triggers:{trackPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},metrika:{transport:{beacon:!0,xhrpost:!0,image:!1},requests:{pageview:"${_watch}?browser-info=${_brInfo}&${_siteInfo}&${_suffix}",notBounce:"${_watch}?browser-info=ar%3A1%3Anb%3A1%3A${_brInfo}&${_suffix}",externalLink:"${_watch}?browser-info=ln%3A1%3A${_brInfo}&${_suffix}",reachGoal:"${_watch}?browser-info=ar%3A1%3A${_brInfo}&${_siteInfo}&${_goalSuffix}",_domain:"https://mc.yandex.ru",_watch:"${_domain}/watch/${counterId}",
_suffix:"page-url=${sourceUrl}&page-ref=${documentReferrer}",_goalSuffix:"page-url=goal%3A%2F%2F${sourceHost}%2F${goalId}&page-ref=${sourceUrl}",_techInfo:"amp%3A1%3Az%3A${timezone}%3Ai%3A${timestamp}%3Arn%3A${random}%3Ala%3A${browserLanguage}%3Aen%3A${documentCharset}%3Arqn%3A${requestCount}%3As%3A${screenWidth}x${screenHeight}x${screenColorDepth}%3Aw%3A${availableScreenWidth}x${availableScreenHeight}%3Ads%3A${_timings}%3Auid%3A${clientId(_ym_uid)}%3Apvid%3A${pageViewId}",_timings:"${domainLookupTime}%2C${tcpConnectTime}%2C${serverResponseTime}%2C${pageDownloadTime}%2C${redirectTime}%2C${navTiming(redirectStart,redirectEnd)}%2C${navRedirectCount}%2C${navTiming(domLoading,domInteractive)}%2C${navTiming(domContentLoadedEventStart,domContentLoadedEventEnd)}%2C${navTiming(navigationStart,domComplete)}%2C${pageLoadTime}%2C${navTiming(loadEventStart,loadEventEnd)}%2C${contentLoadTime}",
_brInfo:"${_techInfo}%3A${_title}",_title:"t%3A${title}",_siteInfo:"site-info=${yaParams}"},triggers:{pageview:{on:"visible",request:"pageview"}}},mparticle:{vars:{eventType:"Unknown",debug:!1,amp_clientId:"CLIENT_ID(mparticle_amp_id)"},requests:{host:"https://pixels.mparticle.com",endpointPath:"/v1/${apiKey}/Pixel",baseParams:"et=${eventType}&amp_id=${amp_clientId}&attrs_k=${eventAttributes_Keys}&attrs_v=${eventAttributes_Values}&ua_k=${userAttributes_Keys}&ua_v=${userAttributes_Values}&ui_t=${userIdentities_Types}&ui_v=${userIdentities_Values}&flags_k=${customFlags_Keys}&flags_v=${customFlags_Values}&ct=${timestamp}&dbg=${debug}&lc=${location}&av=${appVersion}",
pageview:"${host}${endpointPath}?dt=ScreenView&n=${canonicalPath}&hn=${ampdocUrl}&ttl=${title}&${baseParams}",event:"${host}${endpointPath}?dt=AppEvent&n=${eventName}&${baseParams}"},transport:{beacon:!1,xhrpost:!1,image:!0}},oewadirect:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"https://${s}.oewabox.at/j0=,,,r=${canonicalUrl};+,amp=1+cp=${cp}+ssl=1+hn=${canonicalHost};;;?lt=${pageViewId}&x=${screenWidth}x${screenHeight}x24&c=CLIENT_ID(oewa)"},triggers:{pageview:{on:"visible",request:"pageview"}}},
oewa:{transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"${url}?s=${s}&amp=1&cp=${cp}&host=${canonicalHost}&path=${canonicalPath}"},triggers:{pageview:{on:"visible",request:"pageview"}}},parsely:{requests:{host:"https://srv.pixel.parsely.com",basePrefix:"${host}/plogger/?rand=${timestamp}&idsite=${apikey}&url=${ampdocUrl}&urlref=${documentReferrer}&screen=${screenWidth}x${screenHeight}%7C${availableScreenWidth}x${availableScreenHeight}%7C${screenColorDepth}&title=${title}&date=${timestamp}&ampid=${clientId(_parsely_visitor)}",
pageview:"${basePrefix}&action=pageview"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},piano:{requests:{host:"https://api-v3.tinypass.com",basePrefix:"/api/v3",baseSuffix:"&pageview_id=${pageViewId}&rand=${random}&amp_client_id=${clientId}&aid=${aid}",pageview:"${host}${basePrefix}/page/track?url=${canonicalUrl}&referer=${documentReferrer}&content_created=${contentCreated}&content_author=${contentAuthor}&content_section=${contentSection}&timezone_offset=${timezone}&tags=${tags}&amp_url=${ampdocUrl}&screen=${screenWidth}x${screenHeight}${baseSuffix}"}},
quantcast:{vars:{labels:""},requests:{host:"https://pixel.quantserve.com/pixel",pageview:"${host};r=${random};a=${pcode};labels=${labels};fpan=;fpa=${clientId(__qca)};ns=0;ce=1;cm=;je=0;sr=${screenWidth}x${screenHeight}x${screenColorDepth};enc=n;et=${timestamp};ref=${documentReferrer};url=${canonicalUrl}"},triggers:{defaultPageview:{on:"visible",request:"pageview"}},transport:{beacon:!1,xhrpost:!1,image:!0}},adobeanalytics:{transport:{xhrpost:!1,beacon:!1,image:!0},vars:{pageName:"TITLE",host:"",
reportSuites:"",linkType:"o",linkUrl:"",linkName:""},requests:{requestPath:"/b/ss/${reportSuites}/0/amp-1.0/s${random}",basePrefix:"vid=z${clientId(adobe_amp_id)}&ndh=0&ce=${documentCharset}&pageName=${pageName}&g=${ampdocUrl}&r=${documentReferrer}&bh=${availableScreenHeight}&bw=${availableScreenWidth}&c=${screenColorDepth}&j=amp&s=${screenWidth}x${screenHeight}",pageview:"https://${host}${requestPath}?${basePrefix}",click:"https://${host}${requestPath}?${basePrefix}&pe=lnk_${linkType}&pev1=${linkUrl}&pev2=${linkName}"}},
adobeanalytics_nativeConfig:{triggers:{pageLoad:{on:"visible",request:"iframeMessage"}}},infonline:{vars:{sv:"ke",ap:"1"},transport:{beacon:!1,xhrpost:!1,image:!0},requests:{pageview:"${url}?st=${st}&sv=${sv}&ap=${ap}&co=${co}&cp=${cp}&host=${canonicalHost}&path=${canonicalPath}"},triggers:{pageview:{on:"visible",request:"pageview"}}},simplereach:{vars:{pid:"",published_at:"",authors:[],channels:[],tags:[]},requests:{host:"https://edge.simplereach.com",baseParams:"amp=true&pid=${pid}&title=${title}&url=${canonicalUrl}&date=${published_at}&authors=${authors}&channels=${categories}&tags=${tags}&referrer=${documentReferrer}&page_url=${sourceUrl}&user_id=${clientId(sr_amp_id)}&domain=${canonicalHost}",
visible:"${host}/n?${baseParams}",timer:"${host}/t?${baseParams}&t=5000&e=5000"},triggers:{visible:{on:"visible",request:"visible"},timer:{on:"timer",timerSpec:{interval:5,maxTimerLength:1200},request:"timer"}}},segment:{transport:{beacon:!1,xhrpost:!1,image:!0},vars:{anonymousId:"CLIENT_ID(segment_amp_id)"},requests:{host:"https://api.segment.io/v1/pixel",base:"?writeKey=${writeKey}&context.library.name=amp&anonymousId=${anonymousId}&context.locale=${browserLanguage}&context.page.path=${canonicalPath}&context.page.url=${canonicalUrl}&context.page.referrer=${documentReferrer}&context.page.title=${title}&context.screen.width=${screenWidth}&context.screen.height=${screenHeight}",
page:"${host}/page${base}&name=${name}",track:"${host}/track${base}&event=${event}"},triggers:{page:{on:"visible",request:"page"}}},snowplow:{requests:{aaVersion:"amp-0.1",basePrefix:"https://${collectorHost}/i?url=${canonicalUrl}&page=${title}&res=${screenWidth}x${screenHeight}&stm=${timestamp}&tz=${timezone}&aid=${appId}&p=web&tv=${aaVersion}",pageView:"${basePrefix}&e=pv",structEvent:"${basePrefix}&e=se&se_ca=${structEventCategory}&se_ac=${structEventAction}&se_la=${structEventLabel}&se_pr=${structEventProperty}&se_va=${structEventValue}"},
transport:{beacon:!1,xhrpost:!1,image:!0}},webtrekk:{requests:{trackURL:"https://${trackDomain}/${trackId}/wt",parameterPrefix:"?p=432,${contentId},1,${screenWidth}x${screenHeight},${screenColorDepth},1,${timestamp},${documentReferrer},${viewportWidth}x${viewportHeight},0&tz=${timezone}&eid=${clientId(amp-wt3-eid)}&la=${browserLanguage}",parameterSuffix:"&pu=${canonicalUrl}",pageParameter:"&cp1=${pageParameter1}&cp2=${pageParameter2}&cp3=${pageParameter3}&cp4=${pageParameter4}&cp5=${pageParameter5}&cp6=${pageParameter6}&cp7=${pageParameter7}&cp8=${pageParameter8}&cp9=${pageParameter9}&cp10=${pageParameter10}",
pageCategories:"&cg1=${pageCategory1}&cg2=${pageCategory2}&cg3=${pageCategory3}&cg4=${pageCategory4}&cg5=${pageCategory5}&cg6=${pageCategory6}&cg7=${pageCategory7}&cg8=${pageCategory8}&cg9=${pageCategory9}&cg10=${pageCategory10}",pageview:"${trackURL}${parameterPrefix}${pageParameter}${pageCategories}${parameterSuffix}",actionParameter:"&ck1=${actionParameter1}&ck2=${actionParameter2}&ck3=${actionParameter3}&ck4=${actionParameter4}&ck5=${actionParameter5}",event:"${trackURL}${parameterPrefix}&ct=${actionName}${actionParameter}${parameterSuffix}"},
transport:{beacon:!1,xhrpost:!1,image:!0}},mpulse:{requests:{onvisible:"https://${beacon_url}?h.d=${h.d}&h.key=${h.key}&h.t=${h.t}&h.cr=${h.cr}&rt.start=navigation&rt.si=${clientId(amp_mpulse)}&rt.ss=${timestamp}&rt.end=${timestamp}&t_resp=${navTiming(navigationStart,responseStart)}&t_page=${navTiming(responseStart,loadEventStart)}&t_done=${navTiming(navigationStart,loadEventStart)}&nt_nav_type=${navType}&nt_red_cnt=${navRedirectCount}&nt_nav_st=${navTiming(navigationStart)}&nt_red_st=${navTiming(redirectStart)}&nt_red_end=${navTiming(redirectEnd)}&nt_fet_st=${navTiming(fetchStart)}&nt_dns_st=${navTiming(domainLookupStart)}&nt_dns_end=${navTiming(domainLookupEnd)}&nt_con_st=${navTiming(connectStart)}&nt_ssl_st=${navTiming(secureConnectionStart)}&nt_con_end=${navTiming(connectEnd)}&nt_req_st=${navTiming(requestStart)}&nt_res_st=${navTiming(responseStart)}&nt_unload_st=${navTiming(unloadEventStart)}&nt_unload_end=${navTiming(unloadEventEnd)}&nt_domloading=${navTiming(domLoading)}&nt_res_end=${navTiming(responseEnd)}&nt_domint=${navTiming(domInteractive)}&nt_domcontloaded_st=${navTiming(domContentLoadedEventStart)}&nt_domcontloaded_end=${navTiming(domContentLoadedEventEnd)}&nt_domcomp=${navTiming(domComplete)}&nt_load_st=${navTiming(loadEventStart)}&nt_load_end=${navTiming(loadEventEnd)}&v=1&http.initiator=amp&u=${sourceUrl}&amp.u=${ampdocUrl}&r2=${documentReferrer}&scr.xy=${screenWidth}x${screenHeight}"},
triggers:{onvisible:{on:"visible",request:"onvisible"}},transport:{beacon:!1,xhrpost:!1,image:!0},extraUrlParamsReplaceMap:{ab_test:"h.ab",page_group:"h.pg","custom_dimension.":"cdim.","custom_metric.":"cmet."}},linkpulse:{vars:{id:"",pageUrl:"CANONICAL_URL",title:"TITLE",section:"",channel:"amp",type:"",host:"pp.lp4.io",empty:""},requests:{base:"https://${host}",pageview:"${base}/p?i=${id}&r=${documentReferrer}&p=${pageUrl}&s=${section}&t=${type}&c=${channel}&mt=${title}&_t=amp&_r=${random}",pageload:"${base}/pl?i=${id}&ct=${domInteractiveTime}&rt=${pageDownloadTime}&pt=${pageLoadTime}&p=${pageUrl}&c=${channel}&t=${type}&s=${section}&_t=amp&_r=${random}",
ping:"${base}/u?i=${id}&u=${clientId(_lp4_u)}&p=${pageUrl}&uActive=true&isPing=yes&c=${channel}&t=${type}&s=${section}&_t=amp&_r=${random}"},triggers:{pageview:{on:"visible",request:"pageview"},pageload:{on:"visible",request:"pageload"},ping:{on:"timer",timerSpec:{interval:30,maxTimerLength:7200},request:"ping"}},transport:{beacon:!1,xhrpost:!1,image:!0}}};bc.infonline.triggers.pageview.iframePing=!0;bc.adobeanalytics_nativeConfig.triggers.pageLoad.iframePing=!0;
bc.oewa.triggers.pageview.iframePing=!0;var cc=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1];Date.now();function dc(a){return"IntersectionObserver"in a&&"IntersectionObserverEntry"in a&&"intersectionRatio"in a.IntersectionObserverEntry.prototype};function ec(a){return void 0===a||"number"==typeof a&&0<=Math.sign(a)}function fc(a){return void 0===a||"number"==typeof a&&0<=Math.sign(a)&&100>=a}
function gc(a){if(!a.visibilitySpec)return!0;var b=a.visibilitySpec;a=b.selector;var c;if(!(c=!a)){if(c=!(1>a.length?0:0==a.lastIndexOf("#",0)))c=!(4>a.length?0:0==a.lastIndexOf("amp-",0));c=c&&":root"!=a&&":host"!=a}if(c)return p().error("Analytics.Visibility",'Visibility spec requires an id selector, a tag name starting with "amp-" or ":root"'),!1;var d=b.continuousTimeMax,e=b.continuousTimeMin,f=b.totalTimeMax,g=b.totalTimeMin;return ec(e)&&ec(d)&&ec(g)&&ec(f)?d<e||f<g?(p().warn("AMP-ANALYTICS",
"Max value in timing conditions should be more than the min value."),!1):fc(b.visiblePercentageMax)&&fc(b.visiblePercentageMin)?b.visiblePercentageMax<b.visiblePercentageMin?(p().error("Analytics.Visibility","visiblePercentageMax should be greater than visiblePercentageMin"),!1):!0:(p().error("Analytics.Visibility","visiblePercentage conditions should be between 0 and 100."),!1):(p().error("Analytics.Visibility","Timing conditions should be positive integers when specified."),!1)}
function hc(a,b,c,d){if(!c)return null;var e,f;a:{var g=c,h=a.win;if((g=(g.ownerDocument||g).defaultView)&&g!=h&&(g.__AMP_TOP||g)==h)try{f=g.frameElement;break a}catch(u){}f=null}var l=f;if(":host"==b||":root"==b)e=l?la(l):null;else if("closest"==d)e=ka(c,b);else if("scope"==d)e=c.parentElement.querySelector(b);else if("#"==b[0]){var n=l?c.ownerDocument:a;e=n.getElementById(b.slice(1))}if(e){var w=a.contains(l||e);if(w)return e}return null}
function ic(a){this.ampdoc=a;this.C=Object.create(null);this.D=q(this.ampdoc.win,"timer");this.H=[];this.ga=this.L.bind(this);this.za=this.va.bind(this);this.S=this.sa=!1;this.qa=r(this.ampdoc,"resources");this.I=null;this.M=Infinity;this.aa=!1;this.A=z(this.ampdoc);this.ea=this.da=!this.A.isVisible()}function jc(a){if(!a.sa){var b=Ta(a.ampdoc);b.onScroll(a.ga);b.onChanged(a.ga);a.sa=!0}}k=ic.prototype;
k.listenOnce=function(a,b,c,d){var e=this,f=a.selector,f=p().assertElement(hc(this.ampdoc,f,d,a.selectionMethod),"Element not found for visibilitySpec: "+f),g=this.qa.getResourceForElementOptional(f);p().assert(g,"Visibility tracking not supported on element: ",f);jc(this);this.S||(this.A.onVisibilityChanged(this.za),this.S=!0,this.va());var h=g.getId();this.C[h]=this.C[h]||[];var l={};l.tL=Date.now();this.C[h].push({config:a,callback:b,state:l,shouldBeVisible:c});this.H.push(g);null===this.I&&(this.I=
this.D.delay(function(){e.L()},20))};
k.listenOnceV2=function(a,b,c,d){var e=this,f=a.selector,g=p().assertElement(hc(this.ampdoc,f,d,a.selectionMethod),"Element not found for visibilitySpec: "+f),h=this.qa.getResourceForElementOptional(g);p().assert(h,"Visibility tracking not supported on element: ",g);if(!this.$){var l=this.Fa.bind(this);this.$=new this.ampdoc.win.IntersectionObserver(function(a){a.forEach(l)},{threshold:cc})}h.loadedOnce().then(function(){e.$.observe(g);var d=h.getId();e.C[d]=e.C[d]||[];var f={};f.tL=Date.now();e.C[d].push({config:a,
callback:b,state:f,shouldBeVisible:c});e.H.push(h)});c||this.S||(this.A.onVisibilityChanged(function(){if(!e.A.isVisible())for(var a=0;a<e.H.length;a++){var b=e.H[a];if(b.hasLoadedOnce())for(var b=e.C[b.getId()],c=b.length-1;0<=c;c--){var d=b[c];if(!d.shouldBeVisible){var f=d.state,g=f.lCE;kc(g?100*g.intersectionRatio:0,d,!1)&&(lc(e,f,g.boundingClientRect),d.callback(f),b.splice(c,1))}}}}),this.S=!0)};
k.Fa=function(a){for(var b=this,c=this.C[a.target.getResourceId()],d=100*a.intersectionRatio,e={},f=c.length-1;0<=f;e={state:e.state,listener:e.listener},f--){e.listener=c[f];var g=!!e.listener.shouldBeVisible,h=e.listener.config;e.state=e.listener.state;e.state.lCE=a;var l=kc(d,e.listener,g);g&&(l?(e.state.schId&&(this.D.cancel(e.state.schId),e.state.schId=null),lc(this,e.state,a.boundingClientRect),e.listener.callback(e.state),c.splice(f,1)):e.state.iV&&!e.state.schId?(g=mc(this,e.state,h),0>=g||
(e.state.schId=this.D.delay(function(a){return function(){var d=a.state.lCE;kc(100*d.intersectionRatio,a.listener,!0)&&(lc(b,a.state,d.boundingClientRect),a.listener.callback(a.state),c.splice(c.indexOf(a.listener),1))}}(e),g))):!e.state.iV&&e.state.schId&&(this.D.cancel(e.state.schId),e.state.schId=null))}0==c.length&&this.$.unobserve(a.target)};k.va=function(){var a=this.A.getVisibilityState();if("hidden"==a||"paused"==a||"inactive"==a)this.ea=!0;this.L()};
k.L=function(){var a=this;null!=this.I&&(this.D.cancel(this.I),this.I=null);for(var b=[],c=this.H.length-1;0<=c;c--){var d=this.H[c];if(d.hasLoadedOnce()){for(var e=d.element.getIntersectionChangeEntry(),f=e.boundingClientRect,e=ca(e.intersectionRatio)?100*e.intersectionRatio:0,d=this.C[d.getId()],g=d.length-1;0<=g;g--){var h=!!d[g].shouldBeVisible;kc(e,d[g],h)&&this.A.isVisible()==h?(lc(this,d[g].state,f),d[g].callback(d[g].state),d.splice(g,1)):mc(this,d[g].state,d[g].config)}0==d.length&&this.H.splice(c,
1)}else b.push(d.loadedOnce())}null===this.I&&Infinity>this.M&&0<this.M&&(this.I=this.D.delay(function(){a.L()},this.M));0<b.length&&!this.aa&&(Promise.race(b).then(function(){a.aa=!1;a.L()}),this.aa=!0)};
function kc(a,b,c){var d=b.config,e=b.state||{};if(0<a){var f=Date.now()-e.tL;e.firstSeenTime=e.firstSeenTime||f;e.lastSeenTime=f;void 0==e.loadTimeVisibility&&300>f&&(e.loadTimeVisibility=a)}var g=e.iV,h=Date.now()-e.lU;e.iV=!!(a>(d.visiblePercentageMin||0)&&a<=(d.visiblePercentageMax||100));e.iV&&g?nc(e,a,h):!e.iV&&g?(e.maxContinuousVisibleTime=Math.max(e.maxContinuousVisibleTime,e.cT+h),e.lU=-1,e.totalVisibleTime+=h,e.cT=0,e.lastVisibleTime=Date.now()-e.tL):e.iV&&!g&&(e.fistVisibleTime=e.fistVisibleTime||
Date.now()-e.tL,nc(e,a,0));b.state=e;return(c&&e.iV||!c)&&(void 0===d.totalTimeMin||e.totalVisibleTime>=d.totalTimeMin)&&(void 0===d.totalTimeMax||e.totalVisibleTime<=d.totalTimeMax)&&(void 0===d.continuousTimeMin||(e.maxContinuousVisibleTime||0)>=d.continuousTimeMin)&&(void 0===d.continuousTimeMax||(e.maxContinuousVisibleTime||0)<=d.continuousTimeMax)}
function mc(a,b,c){var d=c.continuousTimeMin>b.cT?c.continuousTimeMin-b.cT:0,e=c.totalTimeMin>b.totalVisibleTime?c.totalTimeMin-b.totalVisibleTime:0;a.M=Math.min(a.M,d||Infinity,e||Infinity);return Math.max(d,e)}
function nc(a,b,c){a.lU=Date.now();a.totalVisibleTime=void 0!==a.totalVisibleTime?a.totalVisibleTime+c:0;a.cT=void 0!==a.cT?a.cT+c:0;a.maxContinuousVisibleTime=void 0!==a.maxContinuousVisibleTime?Math.max(a.maxContinuousVisibleTime,a.cT):0;a.minVisiblePercentage=a.minVisiblePercentage?Math.min(a.minVisiblePercentage,b):b;a.maxVisiblePercentage=a.maxVisiblePercentage?Math.max(a.maxVisiblePercentage,b):b;a.lastVisibleTime=Date.now()-a.tL}
function lc(a,b,c){var d=Ta(a.ampdoc);b.elementX=d.getScrollLeft()+c.left;b.elementY=d.getScrollTop()+c.top;b.elementWidth=c.width;b.elementHeight=c.height;c=(c=a.ampdoc.win.performance)&&c.timing&&c.timing.domInteractive?Date.now()-c.timing.domInteractive:null;b.totalTime=c||"";b.loadTimeVisibility=b.loadTimeVisibility||0;void 0!==b.minVisiblePercentage&&(b.minVisiblePercentage=Math.round(100*b.minVisiblePercentage)/100);void 0!==b.maxVisiblePercentage&&(b.maxVisiblePercentage=Math.round(100*b.maxVisiblePercentage)/
100);b.backgrounded=a.ea?"1":"0";b.backgroundedAtStart=a.da?"1":"0";delete b.cT;delete b.lU;delete b.iV;delete b.tL;delete b.schId;delete b.lCE;for(var e in b)b.hasOwnProperty(e)&&(b[e]=String(b[e]))};var pa=/^vars(.+)/,oc=["visible","click","timer","hidden"];function W(a,b){this.type=a;this.vars=b||Object.create(null)}function X(a){var b=this;this.ampdoc=a;this.Ja=dc(a.win)&&Ha(a.win,"visibility-v2");this.T=new ic(this.ampdoc);this.D=q(this.ampdoc.win,"timer");this.A=z(this.ampdoc);this.F=Ta(this.ampdoc);this.ia=new D;this.ra=!1;this.ta=new D;this.W={};this.J={};this.ha=!1;this.D.delay(function(){b.J=void 0},1E4)}
X.prototype.addListener=function(a,b,c){var d=a.on;if(c.ownerDocument.defaultView!=this.ampdoc.win?-1<oc.indexOf(d):1)if("visible"===d)pc(this,b,a,"visible",c);else if("click"===d)a.selector?(this.ha||(this.ha=!0,this.ampdoc.getRootNode().addEventListener("click",this.Da.bind(this))),this.ia.add(qc(b,a.selector))):p().error("Analytics.Instrumentation","Missing required selector on click trigger");else if("scroll"===d)a.scrollSpec?(rc(this,a.scrollSpec,b),a=this.F.getSize(),this.na({top:this.F.getScrollTop(),
left:this.F.getScrollLeft(),width:a.width,height:a.height,relayoutAll:!1,velocity:0})):p().error("Analytics.Instrumentation","Missing scrollSpec on scroll trigger.");else if("timer"===d)sc(a.timerSpec)&&tc(this,b,a.timerSpec);else if("hidden"===d)pc(this,b,a,"hidden",c);else{var e=this.W[d];e||(e=new D,this.W[d]=e);e.add(b);if(this.J){var f=this.J[d];f&&this.D.delay(function(){f.forEach(function(a){b(a)})},1)}}else p().error("Analytics.Instrumentation",'Trigger type "'+d+'" is not allowed in the embed.')};
X.prototype.triggerEvent=function(a,b){b=new W(a,b);if(this.J){var c=this.J[b.type];c||(c=[],this.J[b.type]=c);c.push(b)}(a=this.W[a])&&a.fire(b)};
function pc(a,b,c,d,e){var f="visible"==d,g=c.visibilitySpec;if(g){if(gc(c)){var h=a.Ja?a.T.listenOnceV2.bind(a.T):a.T.listenOnce.bind(a.T);h(g,function(c){var f=hc(a.ampdoc,g.selector,e,g.selectionMethod);if(f){var f=oa(f),h;for(h in f)c[h]=f[h]}b(new W(d,c))},f,e)}}else if(a.A.isVisible()==f)b(new W(d)),c.called=!0;else a.A.onVisibilityChanged(function(){c.called||a.A.isVisible()!=f||(b(new W(d)),c.called=!0)})}X.prototype.Da=function(a){this.ia.fire(a)};X.prototype.na=function(a){this.ta.fire(a)};
function qc(a,b){return function(c){try{var d=c.target;if("*"===b||na(d,b))a(new W("click",oa(d)));else for(;null!=d.parentElement&&"BODY"!=d.parentElement.tagName;)if(d=d.parentElement,na(d,b)){a(new W("click",oa(d)));break}}catch(e){p().error("Analytics.Instrumentation","Bad query selector.",b,e)}}}
function rc(a,b,c){if(Array.isArray(b.verticalBoundaries)||Array.isArray(b.horizontalBoundaries)){a.ra||(a.ra=!0,a.F.onChanged(a.na.bind(a)));var d=function(a,b,d){if(b)for(var e in a)if(!(!a.hasOwnProperty(e)||e>b||a[e])){a[e]=!0;var f=Object.create(null);f[d]=e;c(new W("scroll",f))}},e=uc(b.verticalBoundaries),f=uc(b.horizontalBoundaries);a.ta.add(function(b){d(e,100*(b.top+b.height)/a.F.getScrollHeight(),"verticalScrollBoundary");d(f,100*(b.left+b.width)/a.F.getScrollWidth(),"horizontalScrollBoundary")})}else p().error("Analytics.Instrumentation",
"Boundaries are required for the scroll trigger to work.")}function uc(a){var b={};if(!a||!Array.isArray(a))return b;for(var c=0;c<a.length;c++){var d=a[c];if("number"!==typeof d||!isFinite(d)){p().error("Analytics.Instrumentation","Scroll trigger boundaries must be finite.");break}d=Math.min(5*Math.round(d/5),100);b[d]=!1}return b}
function sc(a){if(a){if(a.hasOwnProperty("interval"))return"number"!==typeof a.interval||.5>a.interval?(p().error("Analytics.Instrumentation","Bad timer interval specification"),!1):a.hasOwnProperty("maxTimerLength")&&("number"!==typeof a.maxTimerLength||0>=a.maxTimerLength)?(p().error("Analytics.Instrumentation","Bad maxTimerLength specification"),!1):!0;p().error("Analytics.Instrumentation","Timer interval specification required");return!1}p().error("Analytics.Instrumentation","Bad timer specification");
return!1}function tc(a,b,c){var d=c.hasOwnProperty("immediate"),e=d?!!c.immediate:!0,f=a.ampdoc.win.setInterval(b.bind(null,new W("timer")),1E3*c.interval);e&&b(new W("timer"));var g=c.maxTimerLength||7200;a.ampdoc.win.setTimeout(a.ampdoc.win.clearInterval.bind(a.ampdoc.win,f),1E3*g)};AMP.registerServiceForDoc("amp-analytics-instrumentation",X);AMP.registerServiceForDoc("activity",Xa);(function(a){return t(a,"cid",cb)})(AMP.win);(function(a){return t(a,"crypto",Ub)})(AMP.win);t(AMP.win,"amp-analytics-variables",U);function vc(a){AMP.BaseElement.call(this,a);this.oa=bc;this.ja=Promise.resolve();this.Ma=this.V=null;this.K={};this.w={};this.pa={};this.Z=null;this.O=t(this.win,"amp-analytics-variables",U)}aa(vc,AMP.BaseElement);k=vc.prototype;k.getPriority=function(){return 1};
k.isAlwaysFixed=function(){return!0};k.isLayoutSupported=function(){return!0};k.buildCallback=function(){var a=this;this.element.setAttribute("aria-hidden","true");this.V=this.element.getAttribute("data-consent-notification-id");null!=this.V&&(this.ja=wa(this.win,"userNotificationManager","amp-user-notification").then(function(b){return b.get(a.V)}))};
k.layoutCallback=function(){var a=this;Sa(this.element);return this.ja.then(this.Aa.bind(this)).then(function(){return ua(qa(a.getAmpDoc()),"amp-analytics-instrumentation")}).then(function(b){a.Z=b}).then(this.Ea.bind(this))};k.detachedCallback=function(){};
k.Ea=function(){var a=this;this.w=wc(this);if(xc(this)){var b=Y(this);return Promise.resolve()}yc(this);if(!this.w.triggers){var c=Y(this);p().error(c,"No triggers were found in the config. No analytics data will be sent.");return Promise.resolve()}zc(this,this.w.extraUrlParams,this.w.extraUrlParamsReplaceMap);var d=[],c={},e;for(e in this.w.triggers){if(ea.call(this.w.triggers,e)){c.trigger=this.w.triggers[e];c.expansionOptions=Ac(this,{},c.trigger,void 0,!0);var f=Y(this);if(!c.trigger){p().error(f,
"Trigger should be an object: ",e);continue}if(!c.trigger.on||!c.trigger.request){p().error(f,'"on" and "request" attributes are required for data to be collected.');continue}zc(this,c.trigger.extraUrlParams,this.w.extraUrlParamsReplaceMap);d.push(Bc(this,c.trigger).then(function(b){return function(c){if(c){if(b.trigger.selector)return a.O.expandTemplate(b.trigger.selector,b.expansionOptions).then(function(c){b.trigger.selector=c;a.Z.addListener(b.trigger,a.la.bind(a,b.trigger),a.element)});a.Z.addListener(b.trigger,
a.la.bind(a,b.trigger),a.element)}}}(c)))}c={trigger:c.trigger,expansionOptions:c.expansionOptions}}return Promise.all(d)};function zc(a,b,c){if(b&&c){var d=0,e;for(e in c){if(16<++d){a=Y(a);p().error(a,"More than 16 extraUrlParamsReplaceMap rules aren't allowed; Skipping the rest");break}for(var f in b){var g=f.replace(e,c[e]);if(f!=g){var h=b[f];delete b[f];b[g]=h}}}}}
k.Aa=function(){var a=this,b=this.element.getAttribute("config");if(!b)return Promise.resolve();Da(b,this.element);var c=Y(this),d={};this.element.hasAttribute("data-credentials")&&(d.credentials=this.element.getAttribute("data-credentials"));var e=this.getAmpDoc();return ra(this.element).expandAsync(b).then(function(a){b=a;return q(e.win,"xhr").fetchJson(b,d)}).then(function(b){a.pa=b},function(a){p().error(c,"Error loading remote config: ",b,a)})};
function wc(a){var b=a.getInlineConfigNoInline(),c={vars:{requestCount:0}},d=a.oa["default"]||{},e=a.oa[a.element.getAttribute("type")]||{};Z(a,d,c);Z(a,e,c,!0);Z(a,b,c);Z(a,a.pa,c);return c}
k.getInlineConfigNoInline=function(){var a={},b=Y(this);try{var c=this.element.children;if(1==c.length){var d=c[0];"SCRIPT"==d.tagName&&"APPLICATION/JSON"==d.getAttribute("type").toUpperCase()?a=JSON.parse(c[0].textContent):p().error(b,'The analytics config should be put in a <script> tag with type="application/json"')}else 1<c.length&&p().error(b,"The tag should contain only one <script> child.")}catch(e){p().error(b,"Analytics config could not be parsed. Is it in a valid JSON format?",e)}return a};
function xc(a){if(!a.w.optout)return!1;var b=a.w.optout.split(".");a=a.win;for(var c=0;c<b.length;c++){if(!a)return!1;a=a[b[c]]}return a()}function yc(a){var b={};if(a.w&&a.w.requests){for(var c in a.w.requests)ea.call(a.w.requests,c)&&(b[c]=a.w.requests[c]);a.K=b;for(var d in a.K)a.K[d]=ya(a.K[d],function(b){return a.K[b]||"${"+b+"}"})}else b=Y(a),p().error(b,"No request strings defined. Analytics data will not be sent from this page.")}
k.la=function(a,b){for(var c=Array.isArray(a.request)?a.request:[a.request],d=[],e=0;e<c.length;e++)d.push(Cc(this,this.K[c[e]],a,b));return Promise.all(d)};
function Cc(a,b,c,d){if(!a.element.ownerDocument.defaultView){var e=Y(a);da().warn(e,"request against destroyed embed: ",c.on);return Promise.resolve()}if(!b)return e=Y(a),p().error(e,"Ignoring event. Request string not found: ",c.request),Promise.resolve();var f=[],g=fa();if(a.w.extraUrlParams||c.extraUrlParams){var h=Ac(a,d,c);Object.assign(g,a.w.extraUrlParams,c.extraUrlParams);var e={},l;for(l in g)e.k=l,"string"==typeof g[e.k]&&f.push(a.O.expandTemplate(g[e.k],h).then(function(a){return function(b){g[a.k]=
b}}(e))),e={k:e.k}}return Promise.all(f).then(function(){var e=b,f=[],h;for(h in g){var l=g[h];null!=l&&(l=a.O.encodeVars(l,h),f.push(encodeURIComponent(h)+"="+l))}f=f.join("&");0<=e.indexOf("${extraUrlParams}")?e=e.replace("${extraUrlParams}",f):f&&(e=e.split("#",2),h=e[0].split("?",2),f=h[0]+(h[1]?"?"+h[1]+"&"+f:"?"+f),e=f+=e[1]?"#"+e[1]:"");b=e;a.w.vars.requestCount++;e=Ac(a,d,c);return a.O.expandTemplate(b,e)}).then(function(b){return ra(a.element).expandAsync(b)}).then(function(b){if(b)if(c.iframePing)p().assert("visible"==
c.on,"iframePing is only available on page view requests."),bb(a.win,b);else{var d=a.win,e=a.w.transport||{};Da(b,"amp-analytics request");var f=y(b).search,g=Object.create(null);if(f){if(0==f.indexOf("?")||0==f.indexOf("#"))f=f.substr(1);for(var f=f.split("&"),h=0;h<f.length;h++){var l=f[h],n=l.indexOf("="),ma;-1!=n?(ma=decodeURIComponent(l.substring(0,n)).trim(),l=decodeURIComponent(l.substring(n+1)).trim()):(ma=decodeURIComponent(l).trim(),l="");ma&&(g[ma]=l)}}p().assert(!("__amp_source_origin"in
g),"Source origin is not allowed in %s",b);e.beacon&&d.navigator.sendBeacon&&d.navigator.sendBeacon(b,"")||e.xhrpost&&ab(d,b)||(e.image?$a(b):p().warn("amp-analytics.Transport","Failed to send request",b,e))}else d=Y(a),p().error(d,"Request not sent. Contents empty.");return b})}
function Bc(a,b){var c=b.sampleSpec,d=Promise.resolve(!0),e=Y(a);if(!c)return d;if(!c.sampleOn)return p().error(e,"Invalid sampleOn value."),d;var f=parseFloat(c.threshold);if(0<=f&&100>=f){var g=a.O.expandTemplate(c.sampleOn,Ac(a,{},b)).then(function(b){return ra(a.element).expandAsync(b)}),h=A(a.win);return Promise.all([g,h]).then(function(a){return a[1].uniform(a[0])}).then(function(a){return 100*a<c.threshold})}p().error(e,"Invalid threshold for sampling.");return d}
function Y(a){return"AmpAnalytics "+(a.element.getAttribute("id")||"<unknown id>")}function Z(a,b,c,d){if(null===c||void 0===c)c={};for(var e in b)p().assert(d||"iframePing"!=e,"iframePing config is only available to vendor config."),ea.call(b,e)&&(Array.isArray(b[e])?(Array.isArray(c[e])||(c[e]=[]),c[e]=Z(a,b[e],c[e],d)):"[object Object]"===ba.call(b[e])?("[object Object]"===ba.call(c[e])||(c[e]={}),c[e]=Z(a,b[e],c[e],d)):c[e]=b[e]);return c}
function Ac(a,b,c,d,e){var f=fa();Z(a,a.w.vars,f);Z(a,c.vars,f);Z(a,b.vars,f);return new Wb(f,d,e)}AMP.registerElement("amp-analytics",vc);
})});
//# sourceMappingURL=amp-analytics-0.1.js.map

